### ISSUE TITLE
No download for 1.82

### ISSUE THREAD

**Issue by SoftwareMonk** [BobSimons/erddap#17]
Not sure if this is intended or not but there is no download/release for 1.82 despite there being a change log entry for it on https://coastwatch.pfeg.noaa.gov/erddap/index.html

**Comment by BobSimons** [comment]
You and others are very attentive.   :-)

Release Candidate:
Yes, I'm testing a release candidate on my main server since it allows me to test ERDDAP in production with 1000+ live datasets in a way that is hard/impossible to do otherwise. As is sometimes the case, I am making a few changes and will test the next release candidate this way, too. Eventually (very soon), I'll do the full public release via GitHub and on the ERDDAP setup.html page. I test the release candidate for at least a few days before every release.

Partial Announcement: 
After I make a release publicly available, I initially only notify a few people -- the people who are related to some change in that version -- so that they can test/comment on the changes. But if you subscribe to this GitHub project, you will be notified of the public release.

Full Announcement: 
About a week after making a version public, I send out the email to the ERDDAP Announcements Mailing List, which I hope includes all ERDDAP administrators.  If you want to be on that mailing list, please email bob.simons at noaa.gov .

Why?
These steps are designed to minimize the penalty that ERDDAP administrators (in particular) pay due to my errors or poor choices. I hope that sounds reasonable.

**Comment by SoftwareMonk** [comment]
Awesome, thanks for the update Bob!

**Comment by BobSimons** [comment]
ERDDAP v1.82 is now available via GitHub.
