### ISSUE TITLE
Compile issues introduced in 1.82

### ISSUE THREAD

**Issue by michaelsmit** [BobSimons/erddap#23]
The change in v1.82 to use String2.directReadFrom88591File() instead of creating a String from a ByteArray in the testing code for datasets introduced many compilation errors.  

For example, line 516 in EDDTableFromPostDatabase.java  (erddap/WEB-INF/classes/gov/noaa/pfel/erddap/dataset/EDDTableFromPostDatabase.java) changed:

before:
results = new String((new ByteArray(EDStatic.fullTestCacheDirectory + tName)).toArray());
after:
results = String2.directReadFrom88591File(EDStatic.fullTestCacheDirectory + tName)).toArray());

The ").toArray())" appears to be a leftover from a search-and-replace to make this change.  It's almost certainly fixed in your local environment already...

**Comment by BobSimons** [comment]
Sorry about that. This has come up before. The underlying problem is: there are classes in the distribution that are not active (for various reasons). As mentioned in the Programmer's Guide ([https://coastwatch.pfeg.noaa.gov/erddap/download/setup.html#programmersGuide]()), when I compile ERDDAP, I delete all .class files then compile TestAll.java (with javacs, which compiles all dependencies). The ensures that all classes that need to be compiled will be compiled, while classes that aren't active won't be compiled. 

Apparently, you and some other people are compiling all the .java files, including the inactive ones. (Fair enough.)

The solution I picked is for me to remove the inactive classes from the distribution or at least rename them so your compiler won't find them. I made an effort to do that after the v1.82 release, so hopefully the problem will be gone with the next release.

Best wishes.

**Comment by michaelsmit** [comment]
Thanks for the prompt response - I thought that might be the case, as some of the files were flagged in comments as being defunct, but I grew concerned when some were not.

My build script follows the documentation; I suspect most people (myself included) encountering the issue are using other tools (IDEs, monitoring/logging code, etc.) that get crotchety when they encounter syntax / compile errors. 

I fully support the decision to not ship the inactive classes!  They will still be in github if we need them.
