### ISSUE TITLE
allow environment variables to alter the setup

### ISSUE THREAD

**Issue by marc-portier** [BobSimons/erddap#53]
Currently setup is driven through setup.xml (read through ResourceBundle2 from cohort) which in turn builds up the EDStatic making those settings available throughout the code.

In modern microservice and container setups (e.g. axiom/docker-erddap, specially in combination with nginx or apache reverse proxy forwarding) however a new separation of concerns is pushing up. Who creates what parts of the setup.xml is not as straightforward any more.  This could be facilitated by allowing the setup to be driven by environment variables like `ERDDAP.baseUrl` and `ERDDAP.baseHttpsUrl` 

These would then be read by `System.getenv`  and injected in stead of the settings in the XML file.  Given that ResourceBundle2 already functions as a decorator for the java native ResourceBundle, this extra layer could maybe added on that level?

**Comment by BobSimons** [comment]
Thank you for your well-thought-out suggestion.

I think of setup.xml as an interface. The admin can use any method they want to make changes to setup.xml (e.g., by hand, by script) and can even specify where setup.xml is located (see
[https://coastwatch.pfeg.noaa.gov/erddap/download/setup.html#erddapContentDirectory](https://coastwatch.pfeg.noaa.gov/erddap/download/setup.html#erddapContentDirectory) ). Then ERDDAP reads from that interface.  The admin has full control of setup.xml. So part of me says: isn't that sufficient?

But I see it would be convenient to use environment variables (or system properties). Are you suggesting that _any_ parameter in setup.xml could be overridden by an environment variable or just a select few parameters? If just a few, which ones do you propose?

Are you specifically suggesting/requesting that these environment variables have names using the form "ERDDAP.[parameterName]"? Do all operating systems support "." in environment variables?  Would "_" be safer as a separator?

Can anyone think of any security issues related to this? I can't, because the environment variables shouldn't be accessible by other users (other than root), but I could easily be missing something.  Some of the parameters need to be kept secret, e.g., flagKeyKey, googleClientID, and orchidClientSecret. 

Any other votes for or against this?

**Comment by mwengren** [comment]
@BobSimons I ran into this issue when trying to run ERDDAP instances on Kubernetes a few years ago.

IIRC, I had to basically script a find/replace process to modify setup.xml on ERDDAP pod deployment using some dedicated Kubernetes pods to execute changes to setup.xml parameters, which got a bit tedious.  There may have been better approaches to that than what I did at the time, but this would make that deploy process much much easier.  

Not sure on the security implications.  Tomcat itself can typically be tuned via user or system environment variables that override config file settings, correct (CATALINA_HOME and such)?

**Comment by abkfenris** [comment]
We're running a few ERDDAP instances in Kubernetes and allowing `setup.xml` configuration with environment variables would be fantastic.

I believe @Dylan-Pugh has basically been keeping two different ` setup.xml`s around. One gets baked into the image for deployment, and then gets mounted over for local testing with a different `baseUrl`. It would be much easier to manage with being able to override `baseUrl` with an environment variable (and less likely to have configuration drift).

Using system properties would make it much harder to use ERDDAP in different contexts as most systems don't have ways to control their configuration natively. Where-as with environment variables, we can set them locally with `export`, in a `docker-compose.yaml` configuration, or with a Kubernetes manifest, or various secret handling machinery like Vault.

As for security, while there is a tendency back away from environment variables for secret configuration right now (its easier to find secrets with an `env` if you take over a process than to find various secret files), if someone gains access to the ERDDAP process, then they also have access to `setup.xml`. 

I believe it's more likely that `setup.xml` is likely to be left with overly generous permissions that would allow a neighboring user to access it, then the process orchestrating ERDDAP is likely to leak environment variables to a neighbor.

**Comment by BobSimons** [comment]
@abkfenris and @mwengren, thanks very much for that information.
@marc-portier, thanks very much for the original request/suggestion and follow-up information.

Okay. I have made it so that any parameter in setup.xml can also be specified (with higher priority) via an environment variable named ERDDAP_parameterName . This feature will be in the next ERDDAP release.

**Comment by BobSimons** [comment]
@marc-portier The just-released v2.14 of ERDDAP has this feature. Please email me (bob.simons at noaa.gov) so we can talk offline.
